### PR TITLE
Added Updated version of app

### PR DESCRIPTION
**Pull request by Shubham9455**
This version of app worked on flutter 3.0.5,It is giving small error because of asset image not provided 
I Solved The Issue https://github.com/adilwahla/Clima-weather-app/issues/1#issue-1393684684

### CODE REVIEW

**Review by adilwahla — APPROVED** [review]
looks okay

**Review by adilwahla — COMMENTED** [review]
cool

**Comment by adilwahla** [comment]
pretty cool if you wanna contribute further you can make documentation better in Readme that describes the app to newbies pretty simple way. And you can add App icon plus new feature like week forecast 
I will create issues later on as well

**Comment by Shubham9455** [comment]
> pretty cool if you wanna contribute further you can make documentation better in Readme that describes the app to newbies pretty simple way. And you can add App icon plus new feature like week forecast 
> I will create issues later on as well 

Hey please add hactober fest accepted tag as well

**Pull request merged**
